apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-microservice-template
spec:
  destination:
    namespace: prod-microservice-template
    server: 'https://kubernetes.default.svc'
  source:
    path: prod
    repoURL: 'https://github.com/itninja-hue/nestjs-k8s-boilerplate-microservice'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true