---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: box
    type: test
  name: {{.Values.benjamin.deployment.name}}
  namespace: {{.Values.general.namespace}}
spec:
  replicas: {{.Values.benjamin.deployment.scale}}
  selector:
    matchLabels:
      app: box
      type: test
  template:
    metadata:
      labels:
        app: box
        type: test
    spec:
      containers:
      - image: itninjahue/box:{{.Values.benjamin.deployment.tag}}
        name: {{.Values.benjamin.deployment.containerName}}
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-microservice-benjamin
              key: database-host
        - name: EVENT_STORE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: configmap-microservice-benjamin
              key: eventstore-host
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: database-password
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-microservice-benjamin
              key: database-port
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap-microservice-benjamin
              key: database-db
        - name : EVENT_STORE_CREDENTIALS_USERNAME
          valueFrom:
            secretKeyRef:
              name: eventstore-credentials
              key: eventstore-user
        - name: EVENT_STORE_CREDENTIALS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eventstore-credentials
              key: eventstore-password
      imagePullSecrets:
      - name: regcred
...