---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.database.secret.name}}
  namespace: {{.Values.general.namespace}}
type: Opaque
data:
  database-user: {{.Values.database.secret.databaseUser}}
  database-password: {{.Values.database.secret.databasePassword}}
...