---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.database.service.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: box
    type: database
  ports:
    - protocol: TCP
      port: {{.Values.database.service.port}}
      targetPort: {{.Values.database.service.port}}
...