---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.eventstore.serviceDatabase.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.general.microserviceName}}
    type: eventstore
  ports:
    - protocol: TCP
      port: {{.Values.eventstore.serviceDatabase.port}}
      targetPort: {{.Values.eventstore.serviceDatabase.port}}
...