---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.benjamin.ingress.ingressName}}
  namespace: {{.Values.general.namespace}}
spec:
  rules:
  - host: {{.Values.benjamin.ingress.host}}
    http:
      paths:
      - backend:
          serviceName: {{.Values.benjamin.service.name}}
          servicePort: {{.Values.benjamin.service.servicePort}}
...