---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMap.name}}
  namespace: {{.Values.general.namespace}}
data:
  database-host: {{.Values.database.deployment.name}}
  eventstore-host: {{.Values.eventstore.deployment.name}}
  database-port: "{{.Values.database.service.port}}"
  database-db: {{.Values.database.deployment.database}}
...