---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.eventstore.secret.name}}
  namespace: {{.Values.general.namespace}}
type: Opaque
data:
  eventstore-user: {{.Values.eventstore.secret.eventstoreUser}}
  eventstore-password: {{.Values.eventstore.secret.eventstorePassword}}
...