---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.microservice.ingress.ingressName}}
  namespace: {{.Values.general.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" 
    nginx.ingress.kubernetes.io/secure-backends: "false"
spec:
  rules:
  {{- if regexMatch "^dev" .Values.general.namespace }}
  - host: {{.Values.microservice.ingress.devhost}}
  {{- else if regexMatch "^preprod" .Values.general.namespace }}
  - host: {{.Values.microservice.ingress.preprodhost}}
  {{- else }}
  - host: {{.Values.microservice.ingress.prodhost}}
  {{- end }}
    http:
      paths:
      - backend:
          serviceName: {{.Values.microservice.service.name}}
          servicePort: {{.Values.microservice.service.servicePort}}
...
