---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.benjamin.service.name}}
  namespace: {{.Values.general.namespace}}
spec:
  selector:
    app: {{.Values.general.microserviceName}}
    type: {{.Values.general.microserviceName}}
  ports:
    - protocol: TCP
      port: {{.Values.benjamin.service.servicePort}}
      targetPort: {{.Values.benjamin.service.serviceTargetPort}}
...