---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.database.secret.name}}
  namespace: {{.Values.general.namespace}}
type: Opaque
data:
  database-user: {{ .Values.database.secret.username | b64enc }}
  database-password: {{ .Values.database.secret.password | b64enc }}
...