---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.database.pvc.name}}
  namespace: {{.Values.general.namespace}}
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName:
  resources:
    requests:
      storage: {{.Values.database.pvc.storage}}
...