---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.eventstore.secret.name}}
  namespace: {{.Values.general.namespace}}
type: Opaque
data:
  eventstore-user: {{ .Values.eventstore.user | b64enc }}
  eventstore-password: {{ .Values.eventstore.password | b64enc }}
...